database:
  dialect: postgres
  host: localhost
  port: 5432
  user: postgres
  name: ads
  password: 111111

server:
  address: 8080

jwt:
  key: example_key
  refreshKey: example_refresh_key
  accessTokenLifespan: 30 # in minutes
  refreshTokenLifespan: 2880 # in minutes

s3:
  bucketName: advertisements.bucket

mailgun:
  domainName: domain_name_example
  APIKey: api_key_example
